# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3911927bb430d11acf9e1787f9c29f59b103459d0c14a9340f070e8950948a1044cf67b0b5c5213757273beebe0d706e73a3b980069b4c3ee97f41ee7b50237e

test:
  secret_key_base: fd40bbc550332d11a9f39e0e796d7945b07f3fd660d47050774360da73d17629e8061f24c6bf3975877f462cc6936cec80db6369cd2e3a156f3e0b15855a286e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
